web/router.ex
defmodule Bugoverflow.Router do
  use Bugoverflow.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bugoverflow.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Bugoverflow do
    pipe_through :browser # Use the default browser stack

    get "/", ArticleController, :index

    resources "/articles", ArticleController do
      resources "/comments", CommentController, only: [:create]
    end
  end

  scope "/auth", Bugoverflow do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", Bugoverflow do
  #   pipe_through :api
  # end
end

web/models/comment.ex
defmodule Bugoverflow.Comment do
  use Bugoverflow.Web, :model

  schema "comments" do
    field :body, :string
    belongs_to :article, Bugoverflow.Article
    belongs_to :user, Bugoverflow.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/controllers/comment_controller.ex
defmodule Bugoverflow.CommentController do
  use Bugoverflow.Web, :controller

  alias Bugoverflow.Article
  plug Bugoverflow.Plugs.RequireAuth when action in [ :create ]

  def create(%{assigns: %{user: user}} = conn, %{"comment" => comment_params, "article_id" => article_id}) do
    article = Repo.get(Article, article_id)
    comment_changeset = Ecto.build_assoc(article, :comments, body: comment_params["body"])
    comment_changeset = Ecto.build_assoc(user, :comments, comment_changeset)

    Repo.insert(comment_changeset)

    conn
    |> put_flash(:info, "Comment posted!")
    |> redirect(to: article_path(conn, :show, article))
  end

end

web/views/comment_view.ex
defmodule Bugoverflow.CommentView do
  use Bugoverflow.Web, :view
end

web/templates/comment/new.html.eex
<h2>Add your Comment</h2>

<%= form_for @comment_changeset, article_comment_path(@conn, :create, @article), fn f -> %>
  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= text_input f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>
  <%= submit "Post", class: "btn btn-primary" %>
<% end %>

web/templates/comment/show.html.eex
<div>
  <%= render Bugoverflow.UserView, "show.html", conn: @conn, user: @comment.user %>
  <%= @comment.body %>
  <%= @comment.updated_at || @comment.inserted_at %>
</div>